### ISSUE TITLE
Customer can add a product to sell

### ISSUE THREAD

**Issue by stevebrownlee** [spooky-oysters/bangazon-web-app#1]
**Given** the user is not authenticated
**When** any view renders
**Then** the *Sell a Product* affordance will not be visible

**Given** the user is authenticated
**When** the user clicks on the *Sell a product* button in the menu bar
**Then** the user will be presented with a product form

**Given** the user can filled in all fields of the product form with valid information
**When** the user clicks the *Sell* button
**Then** the user will be redirected to the product detail view for that product

**Given** the user can filled in all fields of the product form with any invalid information
**When** the user clicks the *Sell* button
**Then** the user will be immediately notified with error information for each invalid value

**Comment by DreRandaci** [comment]
**When** making a new project for the sprint, add `Individual Authentication` during project type selection 
 (MVC Web Application)
**Sell a Product** should be hidden from the navigation bar _until_ a user is authenticated
